# app/config/security.yml

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        OC\UserBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_AUTEUR, ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    
    providers:
        main:
            entity:
                class:    OC\UserBundle\Entity\User
                property: username
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
            pattern:   ^/login$
            anonymous: true 

        main:
            pattern:        ^/
            anonymous:      false
            provider:       main

            form_login:
                    login_path: login
                    check_path: login_check

            logout:
                    path:       logout
                    target:     /platform

    access_control:
                #- { path: ^/admin, roles: ROLE_ADMIN }